// SPDX-License-Identifier: MIT OR Apache-2.0
//! The CUDA launches: one forward kernel, three backward kernels (`kernels/fused_attn.cu`).
//!
//! Everything runs on candle's own stream (and in its context), so ordering against candle's
//! other kernels is the stream's and no synchronisation is needed. The small `D` kernel loads
//! through `CudaDevice::get_or_load_custom_func`; the three tiled kernels through cudarc
//! directly, to raise their dynamic shared-memory limit past 48 KB.

#![allow(unsafe_code)]
// EXPLICIT: a kernel launch is FFI; each `unsafe` block states what the kernel reads and writes.

use candle_core::backend::BackendStorage;
use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock};

use candle_core::cuda_backend::cudarc::driver::sys::CUfunction_attribute;
use candle_core::cuda_backend::cudarc::driver::{
    CudaFunction, CudaModule, LaunchConfig, PushKernelArg,
};
use candle_core::cuda_backend::{CudaDevice, DeviceId, WrapErr};
use candle_core::op::BackpropOp;
use candle_core::{CudaStorage, Error, Layout, Result, Shape, Storage, Tensor};

use crate::{CUDA_HEAD_DIM, FusedAttention, float4_aligned, float4_rows};

/// The PTX, `FUSED_ATTN`, generated by build.rs.
mod ptx {
    #![allow(missing_docs, clippy::missing_docs_in_private_items)]
    include!(concat!(env!("OUT_DIR"), "/ptx.rs"));
}

/// The module name under which candle caches our PTX.
const MODULE: &str = "candle_fused_attn";
/// Threads per block, as `NT` in the kernels.
const THREADS: u32 = 256;
/// Query rows per forward block (`FW_QRYS`).
const FWD_ROWS: usize = 64;
/// Dynamic shared memory of the forward: Q, K, V, P (64 rows each) × 68 floats.
const FWD_SMEM: u32 = 4 * 64 * 68 * 4;
/// Warps per block (one `D` row each in the dot kernel).
const WARPS: usize = 8;

/// `usize → i32` for a kernel argument.
fn i32_of(x: usize) -> Result<i32> {
    i32::try_from(x).map_err(|_| Error::Msg(format!("fused_attention: {x} exceeds i32")))
}

/// `usize → i64` for a kernel stride.
fn i64_of(x: usize) -> Result<i64> {
    i64::try_from(x).map_err(|_| Error::Msg(format!("fused_attention: {x} exceeds i64")))
}

/// `usize → u32` for a grid dimension.
fn u32_of(x: usize) -> Result<u32> {
    u32::try_from(x).map_err(|_| Error::Msg(format!("fused_attention: {x} exceeds u32")))
}

/// The (batch, head, seq) strides of a `[b, h, s, d]` layout.
fn strides(l: &Layout) -> Result<[i64; 3]> {
    match l.stride() {
        &[sb, sh, ss, _] => Ok([i64_of(sb)?, i64_of(sh)?, i64_of(ss)?]),
        other => Err(Error::Msg(format!(
            "fused_attention: rank-4 layout expected, strides {other:?}"
        ))),
    }
}

/// The CUDA-side shape gate.
fn check_head_dim(d: usize) -> Result<()> {
    if d == CUDA_HEAD_DIM {
        Ok(())
    } else {
        Err(Error::Msg(format!(
            "fused_attention: the CUDA kernels take head_dim {CUDA_HEAD_DIM}, got {d}"
        )))
    }
}

/// A grid of `ceil(s / rows) × h × b` blocks of [`THREADS`].
fn grid(s: usize, rows: usize, h: usize, b: usize) -> Result<LaunchConfig> {
    Ok(LaunchConfig {
        grid_dim: (u32_of(s.div_ceil(rows))?, u32_of(h)?, u32_of(b)?),
        block_dim: (THREADS, 1, 1),
        shared_mem_bytes: 0,
    })
}

/// The forward: `[O | L]` as one f32 buffer.
pub fn forward(
    scale: f32,
    causal: bool,
    (b, h, s, d): (usize, usize, usize, usize),
    (sq, lq): (&CudaStorage, &Layout),
    (sk, lk): (&CudaStorage, &Layout),
    (sv, lv): (&CudaStorage, &Layout),
) -> Result<(CudaStorage, Shape)> {
    check_head_dim(d)?;
    if ![lq, lk, lv].iter().all(|l| float4_aligned(l)) {
        return Err(Error::Msg(
            "fused_attention: q, k, v rows must be 16-byte aligned (use fused_attention())".into(),
        ));
    }
    let dev = sq.device().clone();
    let stream = dev.cuda_stream();
    let q = sq.as_cuda_slice::<f32>()?.slice(lq.start_offset()..);
    let k = sk.as_cuda_slice::<f32>()?.slice(lk.start_offset()..);
    let v = sv.as_cuda_slice::<f32>()?.slice(lv.start_offset()..);
    let len = b * s * h * d + b * h * s;
    // SAFETY: every element is written by the kernel (each valid (b, h, i) row writes its d outputs
    // and its L entry).
    let out = unsafe { dev.alloc::<f32>(len)? };
    let (bi, hi, si, ci) = (i32_of(b)?, i32_of(h)?, i32_of(s)?, i32::from(causal));
    let ([q0, q1, q2], [k0, k1, k2], [v0, v1, v2]) = (strides(lq)?, strides(lk)?, strides(lv)?);
    let func = function(&dev, "fattn_fwd_f32_d64", FWD_SMEM)?;
    let mut builder = stream.launch_builder(&func);
    builder.arg(&q).arg(&k).arg(&v).arg(&out);
    builder.arg(&bi).arg(&hi).arg(&si).arg(&scale).arg(&ci);
    builder
        .arg(&q0)
        .arg(&q1)
        .arg(&q2)
        .arg(&k0)
        .arg(&k1)
        .arg(&k2)
        .arg(&v0)
        .arg(&v1)
        .arg(&v2);
    // SAFETY: reads q, k, v through their strides inside their storages (shape-checked), writes
    // `len` floats of `out`.
    let cfg = LaunchConfig {
        shared_mem_bytes: FWD_SMEM,
        ..grid(s, FWD_ROWS, h, b)?
    };
    unsafe { builder.launch(cfg) }.w()?;
    Ok((CudaStorage::wrap_cuda_slice(out, dev), Shape::from(len)))
}

/// The CUDA storage behind a tensor.
fn cuda_of<'a>(name: &str, s: &'a Storage) -> Result<&'a CudaStorage> {
    if let Storage::Cuda(c) = s {
        Ok(c)
    } else {
        Err(Error::Msg(format!(
            "fused_attention: {name} is not on CUDA"
        )))
    }
}

/// A fresh gradient tensor over a `[b, s, h, d]` buffer, returned as its `[b, h, s, d]` view.
fn grad_tensor(
    slice: candle_core::cuda_backend::cudarc::driver::CudaSlice<f32>,
    dev: &CudaDevice,
    (b, h, s, d): (usize, usize, usize, usize),
) -> Result<Tensor> {
    let storage = Storage::Cuda(CudaStorage::wrap_cuda_slice(slice, dev.clone()));
    Tensor::from_storage(storage, (b, s, h, d), BackpropOp::none(), false).transpose(1, 2)
}

/// Dynamic shared memory of the dK/dV kernel: K, V (64 rows), Q, dO, P, dS (32 rows), × 68 floats.
const DKDV_SMEM: u32 = (2 * 64 + 4 * 32) * 68 * 4;
/// Dynamic shared memory of the dQ kernel: Q, dO (64 rows), K, V, dSᵀ (32 rows), × 68 floats.
const DQ_SMEM: u32 = (2 * 64 + 3 * 32) * 68 * 4;
/// Keys per dK/dV block and queries per dQ block.
const BWD_ROWS: usize = 64;

/// Our module, one per device, loaded through cudarc directly: the tiled kernels need more
/// than 48 KB of dynamic shared memory, an attribute candle's `CudaFunc` does not expose. Same
/// context, and launched on candle's stream, so ordering is unchanged.
static MODULES: OnceLock<Mutex<HashMap<DeviceId, Arc<CudaModule>>>> = OnceLock::new();

/// A kernel of our module on `dev`, allowed `smem` bytes of dynamic shared memory.
fn function(dev: &CudaDevice, name: &str, smem: u32) -> Result<CudaFunction> {
    let module = {
        let mut map = MODULES
            .get_or_init(Mutex::default)
            .lock()
            .map_err(|_| Error::Msg("fused_attention: module cache poisoned".into()))?;
        if let Some(m) = map.get(&dev.id()) {
            m.clone()
        } else {
            let m = dev
                .cuda_stream()
                .context()
                .load_module(ptx::FUSED_ATTN.into())
                .w()?;
            map.insert(dev.id(), m.clone());
            m
        }
    };
    let func = module.load_function(name).w()?;
    let bytes = i32::try_from(smem).map_err(|_| Error::Msg("fused_attention: smem".into()))?;
    func.set_attribute(
        CUfunction_attribute::CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES,
        bytes,
    )
    .w()?;
    Ok(func)
}

/// The backward: `D = rowsum(dO ∘ O)`, then dK/dV over key blocks, then dQ over query blocks.
#[allow(clippy::too_many_lines)] // EXPLICIT: three launches with long, flat argument lists.
pub fn backward(
    op: FusedAttention,
    q: &Tensor,
    k: &Tensor,
    v: &Tensor,
    packed: &Tensor,
    grad: &Tensor,
) -> Result<(Tensor, Tensor, Tensor)> {
    let (b, h, s, d) = q.dims4()?;
    check_head_dim(d)?;
    let (q, k, v) = (float4_rows(q)?, float4_rows(k)?, float4_rows(v)?); // no-ops via fused_attention
    let (q_st, lq) = q.storage_and_layout();
    let (k_st, lk) = k.storage_and_layout();
    let (v_st, lv) = v.storage_and_layout();
    let (p_st, lp) = packed.storage_and_layout();
    let (g_st, lg) = grad.storage_and_layout();
    if !lp.is_contiguous() || !lg.is_contiguous() || lg.start_offset() % 4 != 0 {
        return Err(Error::Msg(
            "fused_attention: packed output and its gradient must be contiguous".into(),
        ));
    }
    let (sq, sk, sv) = (
        cuda_of("q", &q_st)?,
        cuda_of("k", &k_st)?,
        cuda_of("v", &v_st)?,
    );
    let (sp, sg) = (cuda_of("output", &p_st)?, cuda_of("gradient", &g_st)?);
    let dev = sq.device().clone();
    let stream = dev.cuda_stream();
    let n = b * s * h * d;

    let qs = sq.as_cuda_slice::<f32>()?.slice(lq.start_offset()..);
    let ks = sk.as_cuda_slice::<f32>()?.slice(lk.start_offset()..);
    let vs = sv.as_cuda_slice::<f32>()?.slice(lv.start_offset()..);
    let ps = sp.as_cuda_slice::<f32>()?.slice(lp.start_offset()..);
    let o = ps.slice(..n);
    let lse = ps.slice(n..);
    let d_o = sg
        .as_cuda_slice::<f32>()?
        .slice(lg.start_offset()..lg.start_offset() + n);

    let (bi, hi, si, ci, scale) = (
        i32_of(b)?,
        i32_of(h)?,
        i32_of(s)?,
        i32::from(op.causal),
        op.scale,
    );
    let ([q0, q1, q2], [k0, k1, k2], [v0, v1, v2]) = (strides(lq)?, strides(lk)?, strides(lv)?);
    // dO is the gradient of O, physically [b, s, h, d] contiguous.
    let (g0, g1, g2) = (i64_of(s * h * d)?, i64_of(d)?, i64_of(h * d)?);

    // SAFETY (all four allocations): every element is written by the kernels below (one D per
    // (b, h, i) row; each dK/dV/dQ row by the block owning it).
    let mut dsum = unsafe { dev.alloc::<f32>(b * h * s)? };
    let mut dq = unsafe { dev.alloc::<f32>(n)? };
    let mut dk = unsafe { dev.alloc::<f32>(n)? };
    let mut dv = unsafe { dev.alloc::<f32>(n)? };

    let dot_cfg = LaunchConfig {
        grid_dim: (u32_of((b * h * s).div_ceil(WARPS))?, 1, 1),
        block_dim: (THREADS, 1, 1),
        shared_mem_bytes: 0,
    };
    let func = dev.get_or_load_custom_func("fattn_bwd_dot_f32_d64", MODULE, ptx::FUSED_ATTN)?;
    let mut builder = func.builder();
    builder.arg(&o).arg(&d_o).arg(&mut dsum);
    builder
        .arg(&bi)
        .arg(&hi)
        .arg(&si)
        .arg(&g0)
        .arg(&g1)
        .arg(&g2);
    // SAFETY: reads n floats of O and dO, writes b·h·s floats of dsum.
    unsafe { builder.launch(dot_cfg) }.w()?;

    let func = function(&dev, "fattn_bwd_dkdv_f32_d64", DKDV_SMEM)?;
    let mut builder = stream.launch_builder(&func);
    builder
        .arg(&qs)
        .arg(&ks)
        .arg(&vs)
        .arg(&d_o)
        .arg(&lse)
        .arg(&dsum)
        .arg(&mut dk)
        .arg(&mut dv);
    builder.arg(&bi).arg(&hi).arg(&si).arg(&scale).arg(&ci);
    builder
        .arg(&q0)
        .arg(&q1)
        .arg(&q2)
        .arg(&k0)
        .arg(&k1)
        .arg(&k2)
        .arg(&v0)
        .arg(&v1)
        .arg(&v2);
    builder.arg(&g0).arg(&g1).arg(&g2);
    let cfg = LaunchConfig {
        shared_mem_bytes: DKDV_SMEM,
        ..grid(s, BWD_ROWS, h, b)?
    };
    // SAFETY: reads q, k, v, dO through their (float4-aligned) strides, L and D; writes n floats
    // each of dK, dV.
    unsafe { builder.launch(cfg) }.w()?;

    let func = function(&dev, "fattn_bwd_dq_f32_d64", DQ_SMEM)?;
    let mut builder = stream.launch_builder(&func);
    builder
        .arg(&qs)
        .arg(&ks)
        .arg(&vs)
        .arg(&d_o)
        .arg(&lse)
        .arg(&dsum)
        .arg(&mut dq);
    builder.arg(&bi).arg(&hi).arg(&si).arg(&scale).arg(&ci);
    builder
        .arg(&q0)
        .arg(&q1)
        .arg(&q2)
        .arg(&k0)
        .arg(&k1)
        .arg(&k2)
        .arg(&v0)
        .arg(&v1)
        .arg(&v2);
    builder.arg(&g0).arg(&g1).arg(&g2);
    let cfg = LaunchConfig {
        shared_mem_bytes: DQ_SMEM,
        ..grid(s, BWD_ROWS, h, b)?
    };
    // SAFETY: as above; writes n floats of dQ.
    unsafe { builder.launch(cfg) }.w()?;

    let dims = (b, h, s, d);
    Ok((
        grad_tensor(dq, &dev, dims)?,
        grad_tensor(dk, &dev, dims)?,
        grad_tensor(dv, &dev, dims)?,
    ))
}
