// SPDX-License-Identifier: MIT OR Apache-2.0
//! The CUDA launches: one forward kernel, two backward kernels (`kernels/fused_attn.cu`).
//!
//! Everything runs on candle's own stream (and in its context), so ordering against candle's
//! other kernels is the stream's and no synchronisation is needed. The module is loaded through
//! cudarc directly (not `CudaDevice::get_or_load_custom_func`): the tiled kernels need more than
//! 48 KB of dynamic shared memory, an attribute candle's `CudaFunc` does not expose.

#![allow(unsafe_code)]
// EXPLICIT: a kernel launch is FFI; each `unsafe` block states what the kernel reads and writes.

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

use candle_core::cuda_backend::cudarc::driver::sys::CUfunction_attribute;
use candle_core::cuda_backend::cudarc::driver::{
    CudaFunction, CudaSlice, CudaView, LaunchConfig, PushKernelArg,
};
use candle_core::cuda_backend::{CudaDevice, DeviceId, WrapErr};
use candle_core::op::BackpropOp;
use candle_core::{CudaStorage, Error, Layout, Result, Storage, Tensor};

use crate::{CUDA_HEAD_DIM, Dims};

/// The PTX, `FUSED_ATTN`, generated by build.rs.
mod ptx {
    #![allow(missing_docs, clippy::missing_docs_in_private_items)]
    include!(concat!(env!("OUT_DIR"), "/ptx.rs"));
}

/// Threads per block, as `NT` in the kernels.
const THREADS: u32 = 256; // TWIN: kernels/fused_attn.cu:NT
/// Warps per block (one `D` row each in the dot kernel), `NT / 32` in the kernels.
// CAST: u32 → usize, 256 / 32 = 8 fits any usize
#[allow(clippy::as_conversions)]
const WARPS: usize = (THREADS / 32) as usize;
/// Query rows per forward block, as `FW_QRYS` in the kernels.
const FWD_QUERIES: usize = 64; // TWIN: kernels/fused_attn.cu:FW_QRYS
/// Keys per forward tile, as `FW_KEYS` in the kernels.
const FWD_KEYS: usize = 64; // TWIN: kernels/fused_attn.cu:FW_KEYS
/// Keys per backward block (one key block), as `KB_KEYS` in the kernels.
const BWD_KEYS: usize = 64; // TWIN: kernels/fused_attn.cu:KB_KEYS
/// Queries per backward tile: one dQ turn counter each, as `KB_QRYS` in the kernels.
const QUERY_TILE: usize = 32; // TWIN: kernels/fused_attn.cu:KB_QRYS
/// The padded row stride of every shared-memory tile, in floats (`head_dim` + 4), as `LD`.
const LD: usize = 68; // TWIN: kernels/fused_attn.cu:LD
/// Dynamic shared memory of the forward, in bytes: Q and P ([`FWD_QUERIES`] rows), K and V
/// ([`FWD_KEYS`] rows), [`LD`] floats each: 69,632 bytes.
// CAST: usize → u32, 69,632 bytes
#[allow(clippy::as_conversions, clippy::cast_possible_truncation)]
const FWD_SMEM: u32 = ((2 * FWD_QUERIES + 2 * FWD_KEYS) * LD * size_of::<f32>()) as u32;
/// Dynamic shared memory of the backward kernel, in bytes: K and V ([`BWD_KEYS`] rows), Q, dO, P
/// and dS ([`QUERY_TILE`] rows), [`LD`] floats each: 69,632 bytes.
// CAST: usize → u32, 69,632 bytes
#[allow(clippy::as_conversions, clippy::cast_possible_truncation)]
const BWD_SMEM: u32 = ((2 * BWD_KEYS + 4 * QUERY_TILE) * LD * size_of::<f32>()) as u32;

/// A `[b, h, s, d]` operand on the device: its first element and its (batch, head, seq) strides
/// in floats (`d` contiguous).
pub struct View<'a> {
    /// The storage from the operand's first element on.
    pub data: CudaView<'a, f32>,
    /// (batch, head, seq) strides.
    pub strides: [i64; 3],
}

/// `usize → i32` for a kernel argument.
fn i32_of(x: usize) -> Result<i32> {
    i32::try_from(x).map_err(|_| Error::Msg(format!("fused_attention: {x} exceeds i32")))
}

/// `usize → i64` for a kernel stride.
fn i64_of(x: usize) -> Result<i64> {
    i64::try_from(x).map_err(|_| Error::Msg(format!("fused_attention: {x} exceeds i64")))
}

/// `usize → u32` for a grid dimension.
fn u32_of(x: usize) -> Result<u32> {
    u32::try_from(x).map_err(|_| Error::Msg(format!("fused_attention: {x} exceeds u32")))
}

/// The CUDA-side shape gate.
fn check_head_dim(d: usize) -> Result<()> {
    if d == CUDA_HEAD_DIM {
        Ok(())
    } else {
        Err(Error::Msg(format!(
            "fused_attention: the CUDA kernels take head_dim {CUDA_HEAD_DIM}, got {d}"
        )))
    }
}

/// A grid of `ceil(s / rows) × h × b` blocks of [`THREADS`] with `smem` bytes of shared memory,
/// `rows` the sequence positions one block owns.
fn grid((b, h, s, _): Dims, rows: usize, smem: u32) -> Result<LaunchConfig> {
    Ok(LaunchConfig {
        grid_dim: (u32_of(s.div_ceil(rows))?, u32_of(h)?, u32_of(b)?),
        block_dim: (THREADS, 1, 1),
        shared_mem_bytes: smem,
    })
}

/// Loaded kernels, per device and name, their shared-memory limit already raised: a launch then
/// costs one map lookup, not a module lookup plus an attribute call.
static FUNCTIONS: OnceLock<Mutex<HashMap<(DeviceId, &'static str), CudaFunction>>> =
    OnceLock::new();

/// The kernel `name` of our module on `dev`, allowed `smem` bytes of dynamic shared memory.
// EXPLICIT: the lock is held across the first load on purpose, so two threads never load twice.
#[allow(clippy::significant_drop_tightening)]
fn function(dev: &CudaDevice, name: &'static str, smem: u32) -> Result<CudaFunction> {
    let mut map = FUNCTIONS
        .get_or_init(Mutex::default)
        .lock()
        .map_err(|_| Error::Msg("fused_attention: kernel cache poisoned".into()))?;
    if let Some(f) = map.get(&(dev.id(), name)) {
        return Ok(f.clone());
    }
    let module = dev
        .cuda_stream()
        .context()
        .load_module(ptx::FUSED_ATTN.into())
        .w()?;
    let func = module.load_function(name).w()?;
    if smem > 0 {
        let bytes = i32::try_from(smem).map_err(|_| Error::Msg("fused_attention: smem".into()))?;
        func.set_attribute(
            CUfunction_attribute::CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES,
            bytes,
        )
        .w()?;
    }
    map.insert((dev.id(), name), func.clone());
    Ok(func)
}

/// The forward: `(O [b, s, h, d] contiguous, L [b, h, s])`.
pub fn forward(
    dev: &CudaDevice,
    scale: f32,
    causal: bool,
    dims: Dims,
    q: &View<'_>,
    k: &View<'_>,
    v: &View<'_>,
) -> Result<(CudaSlice<f32>, CudaSlice<f32>)> {
    let (b, h, s, d) = dims;
    check_head_dim(d)?;
    // SAFETY: every element is written by the kernel (each valid (b, h, i) row writes its d
    // outputs and its L entry).
    let (mut o, mut lse) = unsafe {
        (
            dev.alloc::<f32>(b * s * h * d)?,
            dev.alloc::<f32>(b * h * s)?,
        )
    };
    let (bi, hi, si, ci) = (i32_of(b)?, i32_of(h)?, i32_of(s)?, i32::from(causal));
    let ([q0, q1, q2], [k0, k1, k2], [v0, v1, v2]) = (q.strides, k.strides, v.strides);
    let func = function(dev, "fattn_fwd_f32_d64", FWD_SMEM)?;
    let stream = dev.cuda_stream();
    let mut builder = stream.launch_builder(&func);
    builder
        .arg(&q.data)
        .arg(&k.data)
        .arg(&v.data)
        .arg(&mut o)
        .arg(&mut lse);
    builder.arg(&bi).arg(&hi).arg(&si).arg(&scale).arg(&ci);
    builder
        .arg(&q0)
        .arg(&q1)
        .arg(&q2)
        .arg(&k0)
        .arg(&k1)
        .arg(&k2)
        .arg(&v0)
        .arg(&v1)
        .arg(&v2);
    // SAFETY: reads q, k, v through their strides inside their storages (shape-checked by the
    // caller), writes all of `o` and `lse`.
    unsafe { builder.launch(grid(dims, FWD_QUERIES, FWD_SMEM)?) }.w()?;
    Ok((o, lse))
}

/// The backward into ONE `[b, s, 3, h, d]` buffer (dQ, dK, dV interleaved: the layout of a fused
/// qkv projection's gradient): `D = rowsum(dO ∘ O)` (which also zeroes the dQ turn counters),
/// then one kernel over key blocks writing dK, dV and, in key-block order, dQ.
pub fn backward(
    dev: &CudaDevice,
    (scale, causal): (f32, bool),
    dims: Dims,
    (q, k, v): (&View<'_>, &View<'_>, &View<'_>),
    (o, lse): (&CudaView<'_, f32>, &CudaView<'_, f32>),
    d_o: &View<'_>,
) -> Result<CudaSlice<f32>> {
    let (b, h, s, d) = dims;
    check_head_dim(d)?;
    // SAFETY (all three allocations): every element is written before it is read: one D per
    // (b, h, i) row and one zeroed turn counter per (b, h, query tile), both by the dot kernel; each
    // (b, s) row's dK, dV by the block owning that key, its dQ first by key block 0.
    let (mut dsum, mut dqkv, mut turn) = unsafe {
        (
            dev.alloc::<f32>(b * h * s)?,
            dev.alloc::<f32>(3 * b * s * h * d)?,
            dev.alloc::<i32>(b * h * s.div_ceil(QUERY_TILE))?,
        )
    };
    let (bi, hi, si, ci) = (i32_of(b)?, i32_of(h)?, i32_of(s)?, i32::from(causal));
    let ([q0, q1, q2], [k0, k1, k2], [v0, v1, v2]) = (q.strides, k.strides, v.strides);
    let [g0, g1, g2] = d_o.strides;
    let stream = dev.cuda_stream();

    let func = function(dev, "fattn_bwd_dot_f32_d64", 0)?;
    let mut builder = stream.launch_builder(&func);
    builder.arg(o).arg(&d_o.data).arg(&mut dsum).arg(&mut turn);
    builder
        .arg(&bi)
        .arg(&hi)
        .arg(&si)
        .arg(&g0)
        .arg(&g1)
        .arg(&g2);
    let cfg = LaunchConfig {
        grid_dim: (u32_of((b * h * s).div_ceil(WARPS))?, 1, 1),
        block_dim: (THREADS, 1, 1),
        shared_mem_bytes: 0,
    };
    // SAFETY: reads O and dO (b·s·h·d each, dO through its strides), writes all of dsum and turn.
    unsafe { builder.launch(cfg) }.w()?;

    let func = function(dev, "fattn_bwd_f32_d64", BWD_SMEM)?;
    let mut builder = stream.launch_builder(&func);
    builder
        .arg(&q.data)
        .arg(&k.data)
        .arg(&v.data)
        .arg(&d_o.data)
        .arg(lse)
        .arg(&dsum);
    builder.arg(&mut dqkv).arg(&mut turn);
    builder.arg(&bi).arg(&hi).arg(&si).arg(&scale).arg(&ci);
    builder
        .arg(&q0)
        .arg(&q1)
        .arg(&q2)
        .arg(&k0)
        .arg(&k1)
        .arg(&k2)
        .arg(&v0)
        .arg(&v1)
        .arg(&v2);
    builder.arg(&g0).arg(&g1).arg(&g2);
    // SAFETY: reads q, k, v, dO through their (float4-aligned) strides, L and D; writes all of
    // dqkv (dK, dV by the owning key block; dQ by key block 0, then read-modify-written in
    // key-block order under the turn counters, which it also advances).
    unsafe { builder.launch(grid(dims, BWD_KEYS, BWD_SMEM)?) }.w()?;
    Ok(dqkv)
}

/// The CUDA storage behind a tensor.
pub fn cuda_of<'a>(name: &str, s: &'a Storage) -> Result<&'a CudaStorage> {
    if let Storage::Cuda(c) = s {
        Ok(c)
    } else {
        Err(Error::Msg(format!(
            "fused_attention: {name} is not on CUDA"
        )))
    }
}

/// A `[b, h, s, d]` view over a CUDA storage: `offset` floats past the layout's start, with the
/// given (batch, head, seq) strides.
pub fn view<'a>(
    st: &'a CudaStorage,
    l: &Layout,
    offset: usize,
    [sb, sh, ss]: [usize; 3],
) -> Result<View<'a>> {
    Ok(View {
        data: st
            .as_cuda_slice::<f32>()?
            .slice(l.start_offset() + offset..),
        strides: [i64_of(sb)?, i64_of(sh)?, i64_of(ss)?],
    })
}

/// A history-free tensor over a fresh device buffer.
pub fn tensor_of(slice: CudaSlice<f32>, dev: &CudaDevice, shape: &[usize]) -> Tensor {
    let storage = Storage::Cuda(CudaStorage::wrap_cuda_slice(slice, dev.clone()));
    Tensor::from_storage(storage, shape, BackpropOp::none(), false)
}
